apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-healer
  namespace: self-healing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auto-healer-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","list","update","patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auto-healer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auto-healer-role
subjects:
- kind: ServiceAccount
  name: auto-healer
  namespace: self-healing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-healer
  namespace: self-healing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-healer
  template:
    metadata:
      labels:
        app: auto-healer
    spec:
      serviceAccountName: auto-healer
      containers:
      - name: healer
        image: ritejmule2610/self-healing-ai:v1
        command: ["python", "auto_healer.py"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
