apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-healing-api
  namespace: self-healing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: self-healing-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: self-healing-api
    spec:
      containers:
      - name: api
        image: ritejmule2610/self-healing-api:v1
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
